### ISSUE TITLE
Enhance App Functionality with Additional Models, Views, and Serializers

### ISSUE THREAD

**Issue by tshegofatsoseane** [InternPulse/team-spacex-backend#2]
**Description:**
As part of the ongoing development, we need to enhance our Django app by adding new models, views, and serializers to support additional features. These changes will provide a more comprehensive structure for managing payment transactions, detailed invoice items, client contacts, expenses, notifications, and recurring invoices.

**Changes to be made**
- [x] 1. Add models: PaymentTransaction, InvoiceItem, ClientContact, Notification, and RecurringInvoiceSchedule.
- [x] 2. Implement corresponding views for managing payment transactions, invoice items, client contacts, notifications, and recurring invoices.
- [x] 3. Create serializers for each new model to facilitate data processing and communication with the frontend.

**Additional Details:**
- Ensure that the new models are properly linked with existing models where necessary.
- Implement views that allow users to interact with and manage the new features seamlessly.
- Write tests to verify the functionality and prevent regressions.
- Update documentation to include information about the newly added features.

**Acceptance Criteria:**
- The new models, views, and serializers should be successfully integrated into the app.
- All tests related to the newly added features should pass.
- Documentation should be updated to reflect the changes.

**Comment by VidyaYadavv1519** [comment]
hiii, can you assign me this issue ??

**Comment by tshegofatsoseane** [comment]
> hiii, can you assign me this issue ??

Sure, no problem.

**Comment by tshegofatsoseane** [comment]
All tasks are done, and implemented successfully.
